# Generated by Django 3.2.16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Assignment",
                ),
            ],
            database_operations=[],
        ),
    ]
