# Generated by Django 3.2.25 on 2024-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date', 'end_date'], name='listings_as_start_d_4ddf80_idx'),
        ),
    ]
